src/Tochal.Web/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Tochal.Core.DomainModels.SSOT;
using Tochal.Infrastructure.Services.Test;
using Tochal.Web.Helpers;
using Research.City.Admin.Toolkit;
using Tochal.Infrastructure.Services.Identity;
using System.ComponentModel;
using Alamut.Data.Structure;
using Tochal.Infrastructure.Services;
using DNTCommon.Web.Core;
using System.Reflection;
using Microsoft.AspNetCore.Mvc.Rendering;
using Tochal.Core.DomainModels.Entity;
using Microsoft.AspNetCore.Http;
using AutoMapper;
using Tochal.Core.DomainModels.Entity.Content;
using Tochal.Core.DomainModels.DTO;

namespace Tochal.Web.Controllers.Banks
{
    [Authorize(Policy = ConstantPolicies.DynamicPermission)]
    [DisplayName("مدیریت گالری")]
    public class GalleryController : Controller
    {
        private readonly GalleryService _GalleryService;
        private readonly GroupGalleryService _GroupGalleryService;

        public GalleryController(GalleryService GalleryService, GroupGalleryService GroupGalleryService)
        {
            _GroupGalleryService = GroupGalleryService;
            _GalleryService = GalleryService;
        }

        [DisplayName("مدیریت گالری ")]
        public async Task<IActionResult> Index(GallerySearchViewModel search)
        {
            if (search.GroupGalleryId == 0)
            {
                TempData.AddResult(ServiceResult.Error("آدرس وارد شده اشتباه است!"));
                return RedirectToAction("Index", "Home");
            }
            var conditions = new ConditionHelper<GalleryDTO>();
            conditions.AddCondition(p => p.GroupGalleryId == search.GroupGalleryId);
            var data = await _GalleryService.GetAll(conditions.GetConditionList());

            var TotalCount = await _GalleryService.TotalCount();

            var model = new SearchCriteriaPageModel<List<GalleryDTO>, GallerySearchViewModel, int>(data, search, TotalCount);
            return View(model);
        }

        [DisplayName("مدیریت گالری ")]
        public async Task<IActionResult> clips(GallerySearchViewModel search)
        {
            if (search.GroupGalleryId == 0)
            {
                TempData.AddResult(ServiceResult.Error("آدرس وارد شده اشتباه است!"));
                return RedirectToAction("Index", "Home");
            }
            var conditions = new ConditionHelper<GalleryDTO>();
            conditions.AddCondition(p => p.GroupGalleryId == search.GroupGalleryId);
            var data = await _GalleryService.GetAll(conditions.GetConditionList());

            var TotalCount = await _GalleryService.TotalCount();

            var model = new SearchCriteriaPageModel<List<GalleryDTO>, GallerySearchViewModel, int>(data, search, TotalCount);
            return View(model);
        }

        public IActionResult Create(int GroupGalleryId)
        {
            ViewBag.GroupGalleryId = GroupGalleryId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IFormFile Image, string Alt, int GroupGalleryId, GalleryTypeSSOT GalleryType)
        {
            var vm = new GalleryViewModel() { Alt = Alt, GroupGalleryId = GroupGalleryId };
            if (Image != null)
            {
                var ImageAddress = await FileUploadHelper.UploadFile(Image);
                if (ImageAddress.Item1.Succeed)
                {
                    vm.Image = ImageAddress.Item2;
                }
            }
            var result = _GalleryService.Create(vm);
            TempData.AddResult(result);

            if (GalleryType == GalleryTypeSSOT.Clip)
                return RedirectToAction(nameof(clips), new { GroupGalleryId });
            return RedirectToAction(nameof(Index), new { GroupGalleryId });

        }

        public async Task<IActionResult> Delete(int id, int GroupGalleryId, GalleryTypeSSOT GalleryType)
        {
            //حذف عکس 
            var result = await _GalleryService.Delete(id);
            TempData.AddResult(result);

            if (GalleryType == GalleryTypeSSOT.Clip)
                return RedirectToAction(nameof(clips), new { GroupGalleryId });
            return RedirectToAction(nameof(Index), new { GroupGalleryId });
        }

        public IActionResult SetFirstImage(int id, int GroupGalleryId)
        {
            _GalleryService.SetFirstImage(id, GroupGalleryId);
            TempData.AddResult(ServiceResult.Okay());
            return RedirectToAction(nameof(Index), new { GroupGalleryId });
        }


        public async Task<IActionResult> Edit(int id)
        {
            var model = await _GalleryService.Find(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(int id, string Alt, int GroupGalleryId, GalleryTypeSSOT GalleryType)
        {
            _GalleryService.EditText(id, Alt);
            TempData.AddResult(ServiceResult.Okay());
            if (GalleryType == GalleryTypeSSOT.Clip)
                return RedirectToAction(nameof(clips), new { GroupGalleryId });
            return RedirectToAction(nameof(Index), new { GroupGalleryId });
        }
    }

}

src/Tochal.Web/Controllers/GroupGalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Tochal.Core.DomainModels.SSOT;
using Tochal.Infrastructure.Services.Test;
using Tochal.Web.Helpers;
using Research.City.Admin.Toolkit;
using Tochal.Infrastructure.Services.Identity;
using System.ComponentModel;
using Alamut.Data.Structure;
using Tochal.Infrastructure.Services;
using DNTCommon.Web.Core;
using System.Reflection;
using Microsoft.AspNetCore.Mvc.Rendering;
using Tochal.Core.DomainModels.Entity;
using Microsoft.AspNetCore.Http;
using AutoMapper;
using Tochal.Core.DomainModels.Entity.Content;
using Tochal.Core.DomainModels.DTO;

namespace Tochal.Web.Controllers.Banks
{
    [Authorize(Policy = ConstantPolicies.DynamicPermission)]
    [DisplayName("مدیریت گالری")]
    public class GroupGalleryController : Controller
    {
        private readonly GroupGalleryService _GroupGalleryService;
        private readonly GalleryEntityService _GalleryEntityService;
        private readonly GalleryService _GalleryService;

        public GroupGalleryController(GroupGalleryService GroupGalleryService, GalleryService GalleryService, GalleryEntityService GalleryEntityService)
        {
            _GroupGalleryService = GroupGalleryService;
            _GalleryService = GalleryService;
            _GalleryEntityService = GalleryEntityService;
        }

        [DisplayName("مدیریت گالری تصاویر ")]
        [GroupingDashboard(GroupingDashboardSSOT.Banks)]
        public async Task<IActionResult> Index(GroupGallerySearchViewModel search)
        {
            var conditions = new ConditionHelper<GroupGalleryDTO>();

            conditions.AddCondition(p => p.GalleryType == GalleryTypeSSOT.Image && p.GalleryForType == GalleryForTypeSSOT.Gallery);

            if (search.Title != null)
                conditions.AddCondition(p => p.Title.Contains(search.Title));

            var data = await _GroupGalleryService.GetAll(conditions.GetConditionList());

            var TotalCount = await _GroupGalleryService.TotalCount();

            var model = new SearchCriteriaPageModel<List<GroupGalleryDTO>, GroupGallerySearchViewModel, int>(data, search, TotalCount);
            return View(model);
        }
         
        [DisplayName("مدیریت گالری تصاویر محتوا ")]
        [GroupingDashboard(GroupingDashboardSSOT.Content)]
        public async Task<IActionResult> IndexGalleries(GroupGallerySearchViewModel search)
        {
            var conditions = new ConditionHelper<GroupGalleryDTO>();

            conditions.AddCondition(p => p.GalleryType == GalleryTypeSSOT.Image&& p.GalleryForType == GalleryForTypeSSOT.Content);

            if (search.Title != null)
                conditions.AddCondition(p => p.Title.Contains(search.Title));

            var data = await _GroupGalleryService.GetAll(conditions.GetConditionList());

            var TotalCount = await _GroupGalleryService.TotalCount();

            var model = new SearchCriteriaPageModel<List<GroupGalleryDTO>, GroupGallerySearchViewModel, int>(data, search, TotalCount);
            return View(model);
        }

        [DisplayName("مدیریت گالری کلیپ ")]
        [GroupingDashboard(GroupingDashboardSSOT.Banks)]
        public async Task<IActionResult> Clips(GroupGallerySearchViewModel search)
        {
            var conditions = new ConditionHelper<GroupGalleryDTO>();

            conditions.AddCondition(p => p.GalleryType == GalleryTypeSSOT.Clip && p.GalleryForType == GalleryForTypeSSOT.Gallery);

            if (search.Title != null)
                conditions.AddCondition(p => p.Title.Contains(search.Title));

            var data = await _GroupGalleryService.GetAll(conditions.GetConditionList());

            var TotalCount = await _GroupGalleryService.TotalCount();

            var model = new SearchCriteriaPageModel<List<GroupGalleryDTO>, GroupGallerySearchViewModel, int>(data, search, TotalCount);
            return View(model);
        }

        //public async Task<IActionResult> Create(GalleryTypeSSOT GalleryType)
        //{
        //    ViewBag.GalleryType = GalleryType;
        //    return View();
        //}

        [HttpPost]
        public async Task<IActionResult> Create(GroupGalleryViewModel vm,IFormFile ImageFile)
        {
            if (ImageFile != null)
            {
                var headerImageAddress = await FileUploadHelper.UploadFile(ImageFile);
                if (headerImageAddress.Item1.Succeed)
                {
                    vm.Image = headerImageAddress.Item2;
                }
            }

            var result = _GroupGalleryService.Create(vm);
            TempData.AddResult(result);

            if (vm.GalleryForType == GalleryForTypeSSOT.Gallery)
            {
                if (vm.GalleryType == GalleryTypeSSOT.Image)
                    return RedirectToAction(nameof(Index));
                return RedirectToAction(nameof(Clips));
            }
            else
            {
                return RedirectToAction(nameof(IndexGalleries));

            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            var model = await _GroupGalleryService.Find(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(GroupGalleryViewModel vm, int id,IFormFile ImageFile)
        {
            if (ImageFile != null)
            {
                var headerImageAddress = await FileUploadHelper.UploadFile(ImageFile);
                if (headerImageAddress.Item1.Succeed)
                {
                    vm.Image = headerImageAddress.Item2;
                }
            }

            var model =await _GroupGalleryService.Find(id);
            var result = await _GroupGalleryService.Edit(id, vm);
            TempData.AddResult(result);

            if (model.GalleryForType == GalleryForTypeSSOT.Gallery)
            {
                if (model.GalleryType == GalleryTypeSSOT.Image)
                    return RedirectToAction(nameof(Index));
                return RedirectToAction(nameof(Clips));
            }
            else
            {
                return RedirectToAction(nameof(IndexGalleries));

            }
        }

        public async Task<IActionResult> Delete(int id, GalleryTypeSSOT GalleryType, GalleryForTypeSSOT GalleryForType)
        {
            try
            {

                if (GalleryForType==GalleryForTypeSSOT.Content)
                {
                    _GalleryEntityService.RemoveByGroupGalleryId(GalleryType, GalleryContentTypeSSOT.Content, id);

                }
                else
                {
                    _GalleryEntityService.RemoveByGroupGalleryId(GalleryType, GalleryContentTypeSSOT.Menu, id);

                }

                //حذف عکس پیشفرض
                _GalleryService.RemoveFirstImage(id);
            
                //حذف تمام عکس هاش
                _GalleryService.RemoveAllByGroupGalleryId(id);
                
                var result = await _GroupGalleryService.Delete(id);
                TempData.AddResult(result);

                if (GalleryForType == GalleryForTypeSSOT.Gallery)
                {
                    if (GalleryType == GalleryTypeSSOT.Image)
                        return RedirectToAction(nameof(Index));
                    return RedirectToAction(nameof(Clips));
                }
                else
                {
                    return RedirectToAction(nameof(IndexGalleries));

                }
            }
            catch (Exception)
            {

                throw;
            }
        }

    }
}

src/Tochal.Web/Views/GroupGallery/Clips.cshtml
@using System.Collections.Generic
@using Alamut.Data.Paging
@using Tochal.Core.DomainModels.SSOT
@using Tochal.Core.DomainModels.DTO.ContentEntity
@using Tochal.AppService.Helpers
@using Tochal.Core.DomainModels.Entity.Content
@using Tochal.Core.DomainModels.DTO
@inject IOptions<FileConfig> FileConfig

@model SearchCriteriaPageModel<List<GroupGalleryDTO>, GroupGallerySearchViewModel, int>
@{
    ViewBag.Title = " دسته بندی گالری";
    int count = 1;
}

<style>
    table, tr {
        border: 1px solid #ddd;
    }

    table {
        border-radius: 25px;
    }

    td, th {
        padding: 10px;
        text-align: center;
    }

    tfoot td {
        padding: 0px 10px;
    }

    thead {
        background-color: #ddd;
        color: #464646;
    }

    @@media (max-width:990px) {
        .show900 {
            width: 82%;
        }
    }

    @@media (max-width:500px) {
        .show900 {
            width: 100%;
        }
    }
</style>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">داشبورد</a></li>
        <li class="breadcrumb-item active" aria-current="page">دسته بندی گالری</li>
    </ol>
</nav>
<div class="content _page-scroll animate-panel padding-0">
    <div class="col-md-12" style="margin-bottom:10px">
        <div class="col-md-2"></div>
        <div class="col-lg-8">
            <form asp-action="Create" asp-controller="GroupGallery" id="contentForm" class="form-horizontal" enctype="multipart/form-data">
                <input type="hidden" name="GalleryType" value="@GalleryTypeSSOT.Clip" />
                <input type="hidden" name="GalleryForType" value="@GalleryForTypeSSOT.Gallery" />

                <div class="form-group row" dir="rtl">
                    <label dir="rtl" class="control-label col-sm-2"> عنوان:</label>
                    <div class="col-lg-2">
                        <input type="text" class="form-control" name="Title" placeholder=" عنوان">
                    </div>
                    <div class="col col-lg-3">
                        <div class="form-group row" dir="rtl">
                            <label dir="rtl" class="control-label col-sm-3"> تصویر:</label>
                            <div class="col-sm-9">
                                <input type="file" class="form-control" name="ImageFile" required placeholder=" تصویر">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <input type="submit" value="ثبت" class="btn btn-block btn-info">
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="text-center container col-md-12">
        <div class="col-md-2"></div>
        <table class="col-md-8 show900">
            <thead>
                <tr>
                    <th>ردیف</th>
                    <th>عنوان</th>
                    <th>تصویر</th>
                    <th>اقدامات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.PageModel)
                {
                    <tr>
                        <td>@(count++)</td>
                        <td>@item?.Title</td>
                        <td>
                            @if (item.Image != null)
                            {
                                <div style="width:100px;height:100px;position:relative;margin:auto;overflow:hidden">
                                    <img src="@FileConfig.Value.WebAddress@item.Image" style="width:100%;height:100%" />

                                </div>
                            }
                        </td>
                        <td>
                            <a asp-action="clips" asp-controller="Gallery" asp-route-GroupGalleryId="@item.Id"><i class="fa fa-image fa-lg text-success margin-left-10" data-toggle="tooltip" title="مدیریت کلیپ ها"></i></a>
                            <a asp-action="Edit" asp-controller="GroupGallery" asp-route-id="@item.Id"><i class="fa fa-edit fa-lg text-info margin-left-10" data-toggle="tooltip" title="ویرایش نام"></i></a>
                            <a asp-action="Delete" asp-controller="GroupGallery" asp-route-GalleryType="@GalleryTypeSSOT.Clip" asp-route-GalleryForType="@GalleryForTypeSSOT.Gallery"  asp-route-id="@item.Id" data-role="confirm"><i class="fa fa-trash fa-lg text-danger" aria-hidden="true" data-toggle="tooltip" title="حذف گالری"></i></a>
                        </td>
                    </tr>
                }

            </tbody>
            <tfoot>

                <tr>
                    <td colspan="5">
                        <nav aria-label="..." style="height:60px">
                            <ul class="pagination">
                                <li class="page-item disabled">
                                    <span class="page-link">««</span>
                                </li>
                                <li class="page-item disabled">
                                    <span class="page-link">«</span>
                                </li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item">
                                    <span class="page-link" style="padding:3px 12px">
                                        <input type="text" name="" value="2" class="form-control" style="background-color:#3498db;height: 23px;width: 50px;text-align: center;" />
                                        @*<span class="sr-only">(current)</span>*@
                                    </span>
                                    <span class="hide goToPage">
                                        <input type="text" name="" value="2" class="form-control" />
                                    </span>
                                </li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">»</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="#">»»</a>
                                </li>
                            </ul>
                        </nav>
                        <div class="text-center size-10">
                            تعداد کل صفحات: <span>@Model.TotalCount</span>
                        </div>
                    </td>
                </tr>

            </tfoot>
        </table>
    </div>
</div>

src/Tochal.Web/Views/GroupGallery/Index.cshtml
@using System.Collections.Generic
@using Alamut.Data.Paging
@using Tochal.Core.DomainModels.SSOT
@using Tochal.Core.DomainModels.DTO.ContentEntity
@using Tochal.AppService.Helpers
@using Tochal.Core.DomainModels.Entity.Content
@using Tochal.Core.DomainModels.DTO
@model SearchCriteriaPageModel<List<GroupGalleryDTO>, GroupGallerySearchViewModel, int>
@{
    ViewBag.Title = " دسته بندی گالری";
    int count = 1;
}

<style>
    table, tr {
        border: 1px solid #ddd;
    }

    table {
        border-radius: 25px;
    }

    td, th {
        padding: 10px;
        text-align: center;
    }

    tfoot td {
        padding: 0px 10px;
    }

    thead {
        background-color: #ddd;
        color: #464646;
    }
    @@media (max-width:990px){
         .show900{
             width:82%;
         }
    }
    @@media (max-width:500px){
         .show900{
             width:100%;
         }
    }
</style>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">داشبورد</a></li>
        <li class="breadcrumb-item active" aria-current="page">دسته بندی گالری</li>
    </ol>
</nav>
<div class="content _page-scroll animate-panel padding-0">
    <div class="col-md-12" style="margin-bottom:10px">
        <div class="col-md-2"></div>
        <div class="col-lg-8"> 
            <form asp-action="Create" asp-controller="GroupGallery" id="contentForm" class="form-horizontal" enctype="multipart/form-data">
                <input type="hidden" name="GalleryType" value="@GalleryTypeSSOT.Image" />
                <input type="hidden" name="GalleryForType" value="@GalleryForTypeSSOT.Gallery" />

                <div class="form-group row" dir="rtl">
                    <label dir="rtl" class="control-label col-sm-2"> عنوان:</label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" name="Title" placeholder=" عنوان">
                    </div>
                    <div class="col-md-3">
                        <input type="submit" value="ثبت" class="btn btn-block btn-info">
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="text-center container col-md-12">
        <div class="col-md-2"></div>
        <table class="col-md-8 show900">
            <thead>
                <tr>
                    <th>ردیف</th>
                    <th>عنوان</th>
                    <th>اقدامات</th>
                </tr>
            </thead>
            <tbody>
               
                @foreach (var item in Model.PageModel)
                {
                    <tr>
                        <td>@(count++)</td>
                        <td>@item?.Title</td>
                        <td>
                            <a asp-action="Index" asp-controller="Gallery" asp-route-GroupGalleryId="@item.Id"><i class="fa fa-image fa-lg text-success margin-left-10" data-toggle="tooltip" title="مدیریت تصاویر"></i></a>
                            <a asp-action="Edit" asp-controller="GroupGallery" asp-route-id="@item.Id"><i class="fa fa-edit fa-lg text-info margin-left-10" data-toggle="tooltip" title="ویرایش نام"></i></a>
                            <a asp-action="Delete" asp-controller="GroupGallery" asp-route-GalleryType="@GalleryTypeSSOT.Image"asp-route-GalleryForType="@GalleryForTypeSSOT.Gallery" asp-route-id="@item.Id" data-role="confirm"><i class="fa fa-trash fa-lg text-danger" aria-hidden="true" data-toggle="tooltip" title="حذف گالری"></i></a>
                        </td>
                    </tr>
                }

            </tbody>
            <tfoot>

                <tr>
                    <td colspan="5">
                        <nav aria-label="..." style="height:60px">
                            <ul class="pagination">
                                <li class="page-item disabled">
                                    <span class="page-link">««</span>
                                </li>
                                <li class="page-item disabled">
                                    <span class="page-link">«</span>
                                </li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item">
                                    <span class="page-link" style="padding:3px 12px">
                                        <input type="text" name="" value="2" class="form-control" style="background-color:#3498db;height: 23px;width: 50px;text-align: center;" />
                                        @*<span class="sr-only">(current)</span>*@
                                    </span>
                                    <span class="hide goToPage">
                                        <input type="text" name="" value="2" class="form-control" />
                                    </span>
                                </li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">»</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="#">»»</a>
                                </li>
                            </ul>
                        </nav>
                        <div class="text-center size-10">
                            تعداد کل صفحات: <span>@Model.TotalCount</span>
                        </div>
                    </td>
                </tr>

            </tfoot>
        </table>
    </div>
</div>

src/Tochal.Web/Views/GroupGallery/IndexGalleries.cshtml
@using System.Collections.Generic
@using Alamut.Data.Paging
@using Tochal.Core.DomainModels.SSOT
@using Tochal.Core.DomainModels.DTO.ContentEntity
@using Tochal.AppService.Helpers
@using Tochal.Core.DomainModels.Entity.Content
@using Tochal.Core.DomainModels.DTO
@using Tochal.Core.DomainModels.Entity.Content
@model SearchCriteriaPageModel<List<GroupGalleryDTO>, GroupGallerySearchViewModel, int>
@{
    ViewBag.Title = " دسته بندی گالری";
    int count = 1;
}

<style>
    table, tr {
        border: 1px solid #ddd;
    }

    table {
        border-radius: 25px;
    }

    td, th {
        padding: 10px;
        text-align: center;
    }

    tfoot td {
        padding: 0px 10px;
    }

    thead {
        background-color: #ddd;
        color: #464646;
    }
    @@media (max-width:990px){
         .show900{
             width:82%;
         }
    }
    @@media (max-width:500px){
         .show900{
             width:100%;
         }
    }
</style>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">داشبورد</a></li>
        <li class="breadcrumb-item active" aria-current="page">دسته بندی گالری</li>
    </ol>
</nav>
<div class="content _page-scroll animate-panel padding-0">
    <div class="col-md-12" style="margin-bottom:10px">
        <div class="col-md-2"></div>
        <div class="col-lg-8"> 
            <form asp-action="Create" asp-controller="GroupGallery" id="contentForm" class="form-horizontal" enctype="multipart/form-data">
                <input type="hidden" name="GalleryType" value="@GalleryTypeSSOT.Image" />
                <input type="hidden" name="GalleryForType" value="@GalleryForTypeSSOT.Content" />

                <div class="form-group row" dir="rtl">
                    <label dir="rtl" class="control-label col-sm-2"> عنوان:</label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" name="Title" placeholder=" عنوان">
                    </div>
                    <div class="col-md-3">
                        <input type="submit" value="ثبت" class="btn btn-block btn-info">
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="text-center container col-md-12">
        <div class="col-md-2"></div>
        <table class="col-md-8 show900">
            <thead>
                <tr>
                    <th>ردیف</th>
                    <th>عنوان</th>
                    <th>اقدامات</th>
                </tr>
            </thead>
            <tbody>
               
                @foreach (var item in Model.PageModel)
                {
                    <tr>
                        <td>@(count++)</td>
                        <td>@item?.Title</td>
                        <td>
                            <a asp-action="Index" asp-controller="Gallery" asp-route-GroupGalleryId="@item.Id"><i class="fa fa-image fa-lg text-success margin-left-10" data-toggle="tooltip" title="مدیریت تصاویر"></i></a>
                            <a asp-action="Edit" asp-controller="GroupGallery" asp-route-id="@item.Id"><i class="fa fa-edit fa-lg text-info margin-left-10" data-toggle="tooltip" title="ویرایش نام"></i></a>
                            <a asp-action="Delete" asp-controller="GroupGallery" asp-route-GalleryType="@GalleryTypeSSOT.Image"asp-route-GalleryForType="@GalleryForTypeSSOT.Content"  asp-route-id="@item.Id" data-role="confirm"><i class="fa fa-trash fa-lg text-danger" aria-hidden="true" data-toggle="tooltip" title="حذف گالری"></i></a>
                        </td>
                    </tr>
                }

            </tbody>
            <tfoot>

                <tr>
                    <td colspan="5">
                        <nav aria-label="..." style="height:60px">
                            <ul class="pagination">
                                <li class="page-item disabled">
                                    <span class="page-link">««</span>
                                </li>
                                <li class="page-item disabled">
                                    <span class="page-link">«</span>
                                </li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item">
                                    <span class="page-link" style="padding:3px 12px">
                                        <input type="text" name="" value="2" class="form-control" style="background-color:#3498db;height: 23px;width: 50px;text-align: center;" />
                                        @*<span class="sr-only">(current)</span>*@
                                    </span>
                                    <span class="hide goToPage">
                                        <input type="text" name="" value="2" class="form-control" />
                                    </span>
                                </li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">»</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="#">»»</a>
                                </li>
                            </ul>
                        </nav>
                        <div class="text-center size-10">
                            تعداد کل صفحات: <span>@Model.TotalCount</span>
                        </div>
                    </td>
                </tr>

            </tfoot>
        </table>
    </div>
</div>