src/Tochal.Web/Controllers/SeasonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Tochal.Core.DomainModels.SSOT;
using Tochal.Infrastructure.Services.Test;
using Tochal.Web.Helpers;
using Research.City.Admin.Toolkit;
using Tochal.Infrastructure.Services.Identity;
using System.ComponentModel;
using Alamut.Data.Structure;
using Tochal.Infrastructure.Services;
using DNTCommon.Web.Core;
using System.Reflection;
using Microsoft.AspNetCore.Mvc.Rendering;
using Tochal.Core.DomainModels.Entity;
using Microsoft.AspNetCore.Http;
using AutoMapper;
using Tochal.Core.DomainModels.Entity.Content;
using Tochal.Core.DomainModels.DTO;

namespace Tochal.Web.Controllers.Banks
{
    [Authorize(Policy = ConstantPolicies.DynamicPermission)]
    [DisplayName("مدیریت فصل ها")]
    public class SeasonController : Controller
    {
        private readonly SeasonService _SeasonService;

        public SeasonController(SeasonService SeasonService)
        {
            _SeasonService = SeasonService;
        }
        [DisplayName("مدیریت فصل ها")]
        [GroupingDashboard(GroupingDashboardSSOT.FirstPage)]
        public IActionResult Index()
        {
            return View();
        }

        [DisplayName("فصل پاییز ")]
        public IActionResult Winter()
        {
            var model = _SeasonService.Get();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateWinter(Season season, IFormFile WinterHeaderImage, IFormFile WinterHeaderMobileImage
             , string WinterHeaderImageName, string WinterHeaderMobileImageName)
        {
            if (WinterHeaderImage != null)
            {
                var headerImageAddress = await FileUploadHelper.UploadFile(WinterHeaderImage);
                if (headerImageAddress.Item1.Succeed)
                {
                    season.WinterHeaderImage = headerImageAddress.Item2;
                }
            }
            else if (WinterHeaderImageName != null)
            {
                season.WinterHeaderImage = WinterHeaderImageName;
            }

            if (WinterHeaderMobileImage != null)
            {
                var headerMobileImageAddress = await FileUploadHelper.UploadFile(WinterHeaderMobileImage);
                if (headerMobileImageAddress.Item1.Succeed)
                {
                    season.WinterHeaderMobileImage = headerMobileImageAddress.Item2;
                }
            }
            else if (WinterHeaderMobileImageName != null)
            {
                season.WinterHeaderMobileImage = WinterHeaderMobileImageName;
            }

            var result=_SeasonService.UpdateWinter(season);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Winter));
        }

        [DisplayName("فصل زمستان ")]
        public IActionResult Autumn()
        {
            var model = _SeasonService.Get();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateAutumn(Season season, IFormFile AutumnHeaderImage, IFormFile AutumnHeaderMobileImage
             , string AutumnHeaderImageName, string AutumnHeaderMobileImageName)
        {
            if (AutumnHeaderImage != null)
            {
                var headerImageAddress = await FileUploadHelper.UploadFile(AutumnHeaderImage);
                if (headerImageAddress.Item1.Succeed)
                {
                    season.AutumnHeaderImage = headerImageAddress.Item2;
                }
            }
            else if (AutumnHeaderImageName != null)
            {
                season.AutumnHeaderImage = AutumnHeaderImageName;
            }

            if (AutumnHeaderMobileImage != null)
            {
                var headerMobileImageAddress = await FileUploadHelper.UploadFile(AutumnHeaderMobileImage);
                if (headerMobileImageAddress.Item1.Succeed)
                {
                    season.AutumnHeaderMobileImage = headerMobileImageAddress.Item2;
                }
            }
            else if (AutumnHeaderMobileImageName != null)
            {
                season.AutumnHeaderMobileImage = AutumnHeaderMobileImageName;
            }

            var result = _SeasonService.UpdateAutumn(season);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Autumn));
        }

        [DisplayName("فصل بهار ")]
        public IActionResult Spring()
        {
            var model = _SeasonService.Get();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSpring(Season season, IFormFile SpringHeaderImage, IFormFile SpringHeaderMobileImage
            ,string SpringHeaderImageName,string SpringHeaderMobileImageName)
        {

            if (SpringHeaderImage != null)
            {
                var headerImageAddress = await FileUploadHelper.UploadFile(SpringHeaderImage);
                if (headerImageAddress.Item1.Succeed)
                {
                    season.SpringHeaderImage = headerImageAddress.Item2;
                }
            }
            else if (SpringHeaderImageName != null)
            {
                season.SpringHeaderImage = SpringHeaderImageName;
            }
             

            if (SpringHeaderMobileImage != null)
            {
                var headerMobileImageAddress = await FileUploadHelper.UploadFile(SpringHeaderMobileImage);
                if (headerMobileImageAddress.Item1.Succeed)
                {
                    season.SpringHeaderMobileImage = headerMobileImageAddress.Item2;
                }
            }
            else if (SpringHeaderMobileImageName != null)
            {
                season.SpringHeaderMobileImage = SpringHeaderMobileImageName;
            }

            var result = _SeasonService.UpdateSpring(season);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Spring));
        }

        [DisplayName("فصل تابستان ")]
        public IActionResult Summer()
        {
            var model = _SeasonService.Get();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSummer(Season season, IFormFile SummerHeaderImage, IFormFile SummerHeaderMobileImage
            , string SummerHeaderImageName, string SummerHeaderMobileImageName)
        {
            if (SummerHeaderImage != null)
            {
                var headerImageAddress = await FileUploadHelper.UploadFile(SummerHeaderImage);
                if (headerImageAddress.Item1.Succeed)
                {
                    season.SummerHeaderImage = headerImageAddress.Item2;
                }
            }
            else if (SummerHeaderImageName != null)
            {
                season.SummerHeaderImage = SummerHeaderImageName;
            }



            if (SummerHeaderMobileImage != null)
            {
                var headerMobileImageAddress = await FileUploadHelper.UploadFile(SummerHeaderMobileImage);
                if (headerMobileImageAddress.Item1.Succeed)
                {
                    season.SummerHeaderMobileImage = headerMobileImageAddress.Item2;
                }
            }
            else if (SummerHeaderMobileImageName != null)
            {
                season.SummerHeaderMobileImage = SummerHeaderMobileImageName;
            }

            var result = _SeasonService.UpdateSummer(season);
            TempData.AddResult(result);
            return RedirectToAction(nameof(Summer));
        }

    }

}

src/Tochal.Web/Views/Season/Autumn.cshtml
@using System.Collections.Generic
@using Alamut.Data.Paging
@using Tochal.Core.DomainModels.SSOT
@using Tochal.Core.DomainModels.DTO.ContentEntity
@using Tochal.AppService.Helpers
@using Tochal.Core.DomainModels.Entity.Content
@using Tochal.Core.DomainModels.DTO
@inject IOptions<FileConfig> FileConfig
@model Tochal.Core.DomainModels.Entity.Season
@{
    ViewBag.Title = " فصل پاییز";
    int count = 1;
}

<style>
    table, tr {
        border: 1px solid #ddd;
    }

    table {
        border-radius: 25px;
    }

    td, th {
        padding: 10px;
        text-align: center;
    }

    tfoot td {
        padding: 0px 10px;
    }

    thead {
        background-color: #ddd;
        color: #464646;
    }

    th.active {
        background-color: #d5d5d5;
    }

    th {
        padding: 0;
    }

        th a {
            width: 100%;
            height: 37px;
            display: inline-block;
            line-height: 37px;
            position: relative;
        }

    .fa-sort {
        line-height: 37px;
        position: absolute;
        left: 12px;
        color: #aaa
    }

    h3 {
        font-weight: 900;
        background-color: #e3e3e3;
        border: 1px solid #ccc;
        width: max-content;
        padding: 10px 20px;
        border-radius: 10px 0 0 10px;
        transform: translateX(36px);
    }

    .Create form, .Edit form {
        padding: 20px;
        padding-bottom: 40px;
        border: 1px solid #ccc;
        border-radius: 0px 30px
    }
</style>
<style>
    #picture1,
    #mainVideo {
        width: 100%;
        border-radius: 10px;
        box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.3);
        object-fit: cover;
        max-height: 300px;
    }

    .popup-bg {
        background-color: rgba(0, 0, 0, 0.35);
        width: 100vw;
        height: 100vh;
        position: absolute;
        z-index: 10;
        top: 0;
        display: grid;
        place-items: center;
    }

    .popup-body {
        position: relative;
    }

        .popup-body img,
        .popup-body video {
            max-width: 90vw;
            max-height: 75vh;
        }

    .popup-close {
        display: grid;
        place-items: center;
        background-color: red;
        color: white;
        font-size: 24px;
        width: 35px;
        height: 35px;
        border-radius: 50%;
        position: absolute;
        top: -20px;
        left: -20px;
        box-shadow: 0px 0px 7px #0000004a;
    }

    .hide {
        display: none;
    }
</style>
<style>

    #galley-input-list {
        list-style-type: none;
        display: flex;
        flex-direction: column;
        border: 1px solid #ccc;
        border-radius: 4px;
        text-align: right;
        padding-right: 0;
        background: #fafbfc
    }

        #galley-input-list li {
            background: #f1f3f6;
            padding: 10px;
            margin: 5px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            transition: 0.2s ease;
            user-select: none;
            cursor: pointer;
        }

        #galley-input-list .active {
            background-color: #d3f1ff;
        }
</style>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">داشبور</a></li>
        <li class="breadcrumb-item"><a href="/Season/Index">لیست فصل ها</a></li>
        <li class="breadcrumb-item active" aria-current="page">پاییز</li>
    </ol>
</nav>
<div class="row " style="margin:40px;padding:40px;border:1px solid grey;border-radius: 25px;position: relative;z-index: 0;">

    <!-- Image Section -->

    <div class="col-md-4 pull-right" id="imageSection" style="position: relative;">
        @if (Model.AutumnHeaderImage != null)
        {
            <img src="@FileConfig.Value.WebAddress@Model.AutumnHeaderImage" alt="" id="picture1">

        }
        else
        {

            <img src="~/images/Default.png" alt="" id="picture1">
        }

    </div>

    <!-- Form Section -->

    <div class="col-md-8 pull-left" id="formSection" style="height: 72vh;overflow-y: auto;">

        <form asp-action="UpdateAutumn" asp-controller="Season" class="form-horizontal" method="post" enctype="multipart/form-data">
            <input type="hidden" name="Id" value="@Model?.Id" />

            <div class="form-group row" dir="rtl">
                <label dir="rtl" class="control-label col-sm-3">عنوان:</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="AutumnTitle" value="@Model?.AutumnTitle" placeholder="عنوان">
                </div>
            </div>

            <div class="form-group row" dir="rtl">
                <label dir="rtl" class="control-label col-sm-3">خلاصه محتوا:</label>
                <div class="col-sm-9">
                    <textarea name="AutumnShortDescription" placeholder="خلاصه محتوا" class="form-control">@Model?.AutumnShortDescription</textarea>
                </div>
            </div>
            <div class="form-group row" dir="rtl">
                <label dir="rtl" class="control-label col-sm-3">محتوا:</label>
                <div class="col-sm-9" id="wysiwyg">
                    <textarea required name="AutumnContent" id="AutumnContent" placeholder="محتوا" class="form-control">@Model?.AutumnContent</textarea>
                </div>
            </div>

            <div class="inputs">

                @if (Model.AutumnHeaderImage != null)
                {
                    <div class="form-group row fileDiv" dir="rtl">
                        <label dir="rtl" class="btn btn-primary control-label col-sm-3 text-center" onclick="editFileHandler(this)">تغییر تصویر هدر؟</label>
                        <input type="hidden" name="AutumnHeaderImageName" value="@Model.AutumnHeaderImage" />
                    </div>
                }
                else
                {
                    <div class="form-group row fileDiv" dir="rtl">
                        <label dir="rtl" class="control-label col-sm-3"> تصویر هدر:</label>
                        <div class="col-sm-9">
                            <input type="file" input-id="1" name="AutumnHeaderImage" class="form-control" onchange="checkFile(this)">
                        </div>
                    </div>
                }
            </div>

            <div class="inputs" dir="rtl">
                @if (Model.AutumnHeaderMobileImage != null)
                {
                    <div class="form-group row fileDiv" dir="rtl">
                        <label dir="rtl" class="btn btn-primary control-label col-sm-3 text-center" onclick="editFileHandler(this)">تغییر تصویر موبایل؟</label>
                        <input type="hidden" name="AutumnHeaderMobileImageName" value="@Model.AutumnHeaderMobileImage" />
                    </div>
                }
                else
                {
                    <div class="form-group row fileDiv" dir="rtl">
                        <label dir="rtl" class="control-label col-sm-3">عکس موبایل :</label>
                        <div class="col-sm-9">
                            <input type="file" name="AutumnHeaderMobileImage" class="form-control" />
                        </div>
                    </div>
                }
            </div>

            <div class="form-group">
                <input type="submit" value="ارسال مطلب" class="btn btn-block btn-info">
            </div>
        </form>

    </div>
</div>

<script src="~/js/create-form.js"></script>
<script>
    new FroalaEditor('#AutumnContent', {
        // Set the image upload URL.
        imageUploadURL: '/UploadFiles',

        imageUploadParams: {
            id: 'my_editor'
        }
    })
</script>
<script>
    let editFileHandler = (e) => {
        let confirmD = confirm('آیا مطمئن هستید؟ ( تصویر قبلی شما حذف خواهد شد)');
        let name = $(e).parent().find('[type="hidden"]').attr('name');
        if (confirmD) {
            if (name == "AutumnHeaderImageName") {
                fileinput = `<div class="col-sm-9"><input type="file" input-id="1" name="AutumnHeaderImage" class="form-control" onchange="checkFile(this)"/></div>`;
            }
            else {
                fileinput = `<div class="col-sm-9"><input type="file" input-id="1" name="AutumnHeaderMobileImage" class="form-control"/></div>`;
            }
            $(e).after(fileinput);
            $(e).parent().find('[type="hidden"]').remove();
            $(e).removeAttr('onclick');
        }
    }
</script>

src/Tochal.Web/Views/Season/Index.cshtml
@using System.Collections.Generic
@using Alamut.Data.Paging
@using Tochal.Core.DomainModels.SSOT
@using Tochal.Core.DomainModels.DTO.ContentEntity
@using Tochal.AppService.Helpers
@using Tochal.Core.DomainModels.Entity.Content
@using Tochal.Core.DomainModels.DTO
@inject IOptions<FileConfig> FileConfig
@{
    ViewBag.Title = " فصل ها";
}

<style>
    table, tr {
        border: 1px solid #ddd;
    }

    table {
        border-radius: 25px;
    }

    td, th {
        padding: 10px;
        text-align: center;
    }

    tfoot td {
        padding: 0px 10px;
    }

    thead {
        background-color: #ddd;
        color: #464646;
    }

    th.active {
        background-color: #d5d5d5;
    }

    th {
        padding: 0;
    }

        th a {
            width: 100%;
            height: 37px;
            display: inline-block;
            line-height: 37px;
            position: relative;
        }

    .fa-sort {
        line-height: 37px;
        position: absolute;
        left: 12px;
        color: #aaa
    }

    h3 {
        font-weight: 900;
        background-color: #e3e3e3;
        border: 1px solid #ccc;
        width: max-content;
        padding: 10px 20px;
        border-radius: 10px 0 0 10px;
        transform: translateX(36px);
    }

    .Create form, .Edit form {
        padding: 20px;
        padding-bottom: 40px;
        border: 1px solid #ccc;
        border-radius: 0px 30px
    }
</style>
<style>
    #seasons {
        display: flex;
        justify-content: space-between;
    }

        #seasons a {
            width: 23%;
            margin: 1%;
            display: grid;
            place-items: center;
            border: 1px solid black;
            border-radius: 15px;
            opacity:.5;
            transition:0.3s ease;
            color:white;
            text-shadow:0 0 5px black;
            font-size:24px;
        }

            #seasons a:nth-of-type(1) {
                background: url('http://uupload.ir/files/hil0_210-2105005_spring-desktop-wallpaper-hd-spring-mountain-wallpaper-hd.jpg');
                background-size: cover;
            }

            #seasons a:nth-of-type(2) {
                background: url('http://uupload.ir/files/2joq_146013.jpg');
                background-size: cover;
            }

            #seasons a:nth-of-type(3) {
                background: url('http://uupload.ir/files/ci7b_fall.jpg');
                background-size: cover;
            }

            #seasons a:nth-of-type(4) {
                background: url('http://uupload.ir/files/zodi_1163751.jpg');
                background-size: cover;
            }

            #seasons a:hover {
                opacity:1;
            }
</style>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">داشبور</a></li>
        <li class="breadcrumb-item active" aria-current="page">فصل ها</li>
    </ol>
</nav>
<div class="row " style="margin:40px;padding:40px;border:1px solid grey;border-radius: 25px;position: relative;z-index: 0;">

    <div class="col-md-12" id="seasons" style="height: 50vh;overflow-y: auto;">

        <a href="/Season/Spring">فصل بهار</a>
        <a href="/Season/Summer">فصل تابستان</a>
        <a href="/Season/Autumn">فصل پاییز</a>
        <a href="/Season/Winter">فصل زمستان</a>
    </div>
</div>

src/Tochal.Web/Views/Season/Spring.cshtml
@using System.Collections.Generic
@using Alamut.Data.Paging
@using Tochal.Core.DomainModels.SSOT
@using Tochal.Core.DomainModels.DTO.ContentEntity
@using Tochal.AppService.Helpers
@using Tochal.Core.DomainModels.Entity.Content
@using Tochal.Core.DomainModels.DTO
@inject IOptions<FileConfig> FileConfig
@model Tochal.Core.DomainModels.Entity.Season
@{
    ViewBag.Title = "بهار";
}

<style>
    table, tr {
        border: 1px solid #ddd;
    }

    table {
        border-radius: 25px;
    }

    td, th {
        padding: 10px;
        text-align: center;
    }

    tfoot td {
        padding: 0px 10px;
    }

    thead {
        background-color: #ddd;
        color: #464646;
    }

    th.active {
        background-color: #d5d5d5;
    }

    th {
        padding: 0;
    }

        th a {
            width: 100%;
            height: 37px;
            display: inline-block;
            line-height: 37px;
            position: relative;
        }

    .fa-sort {
        line-height: 37px;
        position: absolute;
        left: 12px;
        color: #aaa
    }

    h3 {
        font-weight: 900;
        background-color: #e3e3e3;
        border: 1px solid #ccc;
        width: max-content;
        padding: 10px 20px;
        border-radius: 10px 0 0 10px;
        transform: translateX(36px);
    }

    .Create form, .Edit form {
        padding: 20px;
        padding-bottom: 40px;
        border: 1px solid #ccc;
        border-radius: 0px 30px
    }
</style>
<style>
    #picture1,
    #mainVideo {
        width: 100%;
        border-radius: 10px;
        box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.3);
        object-fit: cover;
        max-height: 300px;
    }

    .popup-bg {
        background-color: rgba(0, 0, 0, 0.35);
        width: 100vw;
        height: 100vh;
        position: absolute;
        z-index: 10;
        top: 0;
        display: grid;
        place-items: center;
    }

    .popup-body {
        position: relative;
    }

        .popup-body img,
        .popup-body video {
            max-width: 90vw;
            max-height: 75vh;
        }

    .popup-close {
        display: grid;
        place-items: center;
        background-color: red;
        color: white;
        font-size: 24px;
        width: 35px;
        height: 35px;
        border-radius: 50%;
        position: absolute;
        top: -20px;
        left: -20px;
        box-shadow: 0px 0px 7px #0000004a;
    }

    .hide {
        display: none;
    }
</style>
<style>

    #galley-input-list {
        list-style-type: none;
        display: flex;
        flex-direction: column;
        border: 1px solid #ccc;
        border-radius: 4px;
        text-align: right;
        padding-right: 0;
        background: #fafbfc
    }

        #galley-input-list li {
            background: #f1f3f6;
            padding: 10px;
            margin: 5px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            transition: 0.2s ease;
            user-select: none;
            cursor: pointer;
        }

        #galley-input-list .active {
            background-color: #d3f1ff;
        }
</style>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">داشبور</a></li>
        <li class="breadcrumb-item"><a href="/Season/Index">لیست فصل ها</a></li>
        <li class="breadcrumb-item active" aria-current="page">فصل بهار</li>
    </ol>
</nav>
<div class="row " style="margin:40px;padding:40px;border:1px solid grey;border-radius: 25px;position: relative;z-index: 0;">

    <!-- Image Section -->

    <div class="col-md-4 pull-right" id="imageSection" style="position: relative;">
        @if (Model.SpringHeaderImage != null)
        {
            <img src="@FileConfig.Value.WebAddress@Model.SpringHeaderImage" alt="" id="picture1">

        }
        else
        {

            <img src="~/images/Default.png" alt="" id="picture1">
        }

    </div>

    <!-- Form Section -->

    <div class="col-md-8 pull-left" id="formSection" style="height: 72vh;overflow-y: auto;">

        <form asp-action="UpdateSpring" asp-controller="Season" class="form-horizontal" method="post" enctype="multipart/form-data">
            <input type="hidden" name="Id" value="@Model?.Id" />

            <div class="form-group row" dir="rtl">
                <label dir="rtl" class="control-label col-sm-3">عنوان:</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" name="SpringTitle" value="@Model?.SpringTitle" placeholder="عنوان">
                </div>
            </div>

            <div class="form-group row" dir="rtl">
                <label dir="rtl" class="control-label col-sm-3">خلاصه محتوا:</label>
                <div class="col-sm-9">
                    <textarea name="SpringShortDescription" placeholder="خلاصه محتوا" class="form-control">@Model?.SpringShortDescription</textarea>
                </div>
            </div>
            <div class="form-group row" dir="rtl">
                <label dir="rtl" class="control-label col-sm-3">محتوا:</label>
                <div class="col-sm-9" id="wysiwyg">
                    <textarea required name="SpringContent" id="SpringContent" placeholder="محتوا" class="form-control">@Model?.SpringContent</textarea>
                </div>
            </div>

            <div class="inputs">

                @if (Model.SpringHeaderImage != null)
                {
                    <div class="form-group row fileDiv" dir="rtl">
                        <label dir="rtl" class="btn btn-primary control-label col-sm-3 text-center" onclick="editFileHandler(this)">تغییر تصویر هدر؟</label>
                        <input type="hidden" name="SpringHeaderImageName" value="@Model.SpringHeaderImage" />
                    </div>
                }
                else
                {
                    <div class="form-group row fileDiv" dir="rtl">
                        <label dir="rtl" class="control-label col-sm-3"> تصویر هدر:</label>
                        <div class="col-sm-9">
                            <input type="file" input-id="1" name="SpringHeaderImage" class="form-control" onchange="checkFile(this)">
                        </div>
                    </div>
                }
            </div>

            <div class="inputs" dir="rtl">
                @if (Model.SpringHeaderMobileImage != null)
                {
                    <div class="form-group row fileDiv" dir="rtl">
                        <label dir="rtl" class="btn btn-primary control-label col-sm-3 text-center" onclick="editFileHandler(this)">تغییر تصویر موبایل؟</label>
                        <input type="hidden" name="SpringHeaderMobileImageName" value="@Model.SpringHeaderMobileImage" />
                    </div>
                }
                else
                {
                    <div class="form-group row fileDiv" dir="rtl">
                        <label dir="rtl" class="control-label col-sm-3">عکس موبایل :</label>
                        <div class="col-sm-9">
                            <input type="file" name="SpringHeaderMobileImage" class="form-control" />
                        </div>
                    </div>
                }
            </div>

            <div class="form-group">
                <input type="submit" value="ارسال مطلب" class="btn btn-block btn-info">
            </div>
        </form>

    </div>
</div>

<script src="~/js/create-form.js"></script>
<script>
    new FroalaEditor('#SpringContent', {
        // Set the image upload URL.
        imageUploadURL: '/UploadFiles',
        fontFamily: {
            "Verdana,Geneva,sans-serif": 'iranSans'
        },
        imageUploadParams: {
            id: 'my_editor'
        }
    })
</script>
<script>
    let editFileHandler = (e) => {
        let confirmD = confirm('آیا مطمئن هستید؟ ( تصویر قبلی شما حذف خواهد شد)');
        let name = $(e).parent().find('[type="hidden"]').attr('name');
        if (confirmD) {
            if (name == "SpringHeaderImageName") {
                fileinput = `<div class="col-sm-9"><input type="file" input-id="1" name="SpringHeaderImage" class="form-control" onchange="checkFile(this)"/></div>`;
            }
            else {
                fileinput = `<div class="col-sm-9"><input type="file" input-id="1" name="SpringHeaderMobileImage" class="form-control"/></div>`;
            }
            $(e).after(fileinput);
            $(e).parent().find('[type="hidden"]').remove();
            $(e).removeAttr('onclick');
        }
    }
</script>